// Generated by CoffeeScript 1.7.1
(function() {
  emo$.Engine.Emotion = (function() {
    function Emotion() {}

    return Emotion;

  })();

  define(['./helpers/_helpers_.js'], function() {});

}).call(this);

//# sourceMappingURL=_emotion_.map
