// Generated by CoffeeScript 1.7.1
(function() {
  emo$.Engine.Emotion = (function() {
    function Emotion() {}

    return Emotion;

  })();

  define(['./helpers/_helpers_.js', './affect.word.js', './emotion.js', './emotional.state.js', './empathy.scope.js', './synesthesiator.emotion.js'], function() {});

}).call(this);

//# sourceMappingURL=_emotion_.map
