// Generated by CoffeeScript 1.7.1
(function() {
  emo$.Gui = (function() {
    function Gui() {}

    return Gui;

  })();

  define(['./empathy.panel.js']);

}).call(this);

//# sourceMappingURL=_gui_.map
