// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    return emo$.Gui.EmpathyPanel = (function() {
      function EmpathyPanel(appletSize, SynClass, $el) {
        this.$el = $el;
        this.synesthesiator = new SynClass();
        this.synesthesiator.updateMethod(this.$el);
      }

      EmpathyPanel.prototype.fireSynesthesiator = function(text) {
        return this.synesthesiator.synesthesize(text);
      };

      return EmpathyPanel;

    })();
  });

}).call(this);

//# sourceMappingURL=empathy.panel.map
