// Generated by CoffeeScript 1.7.1
(function() {
  emo$.api.inits = (function() {
    function inits() {}

    return inits;

  })();

  define(['./javascript.js'], function() {});

}).call(this);

//# sourceMappingURL=_inits_.map
