// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {

    /*
    * Returns a random number between min and max
     */
    Math.randomRange = function(min, max) {
      return Math.random() * (max - min) + min;
    };

    /*
    * Returns a random integer between min and max
    * Using Math.round() will give you a non-uniform distribution!
     */
    return Math.randomRangeInt = function(min, max) {
      return Math.floor(Math.random() * (max - min + 1)) + min;
    };
  });

}).call(this);

//# sourceMappingURL=javascript.map
