// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {

    /*
    * Returns a random number between min and max
     */
    var empathyScope;
    empathyScope = emo$.Engine.Emotion.EmpathyScope.getInstance();
    $.fn.emo$ = function() {
      return this.text();
    };
    return $.fn.feel$ = function() {
      return empathyScope.feel(this.val());
    };
  });

}).call(this);

//# sourceMappingURL=jquery.map
