// Generated by CoffeeScript 1.7.1
(function() {
  emo$.Engine.Utils = (function() {
    function Utils() {}

    return Utils;

  })();

  define(['./properties.manager.js', './file.reader.js']);

}).call(this);

//# sourceMappingURL=_utils_.map
