// Generated by CoffeeScript 1.7.1
(function() {
  emo$.art.sketch = (function() {
    function sketch() {}

    return sketch;

  })();

  define(['./synemania.js'], function() {});

}).call(this);

//# sourceMappingURL=_sketch_.map
