// Generated by CoffeeScript 1.7.1
(function() {
  emo$.art.utils = (function() {
    function utils() {}

    return utils;

  })();


  /*define [
    './synesketch.palette.js'
  ], () ->
   */

}).call(this);

//# sourceMappingURL=_utils_.map
