// Generated by CoffeeScript 1.7.1
(function() {
  emo$.Engine = (function() {
    function Engine() {}

    return Engine;

  })();

  define(['./utils/_utils_.js', './emotion/_emotion_.js', 'engine/synesketch.state', './synesthesiator.js'], function() {
    return emo$.Engine;
  });

}).call(this);

//# sourceMappingURL=_engine_.map
