// Generated by CoffeeScript 1.7.1
(function() {
  define('engine/synesketch.state', [], function() {
    return emo$.Engine.SynesketchState = (function() {
      function SynesketchState(text) {
        this.text = text;
      }

      SynesketchState.prototype.getText = function() {
        return this.text;
      };

      return SynesketchState;

    })();
  });

}).call(this);

//# sourceMappingURL=synesketch.state.map
