// Generated by CoffeeScript 1.7.1
(function() {
  emo$.Engine.Utils = (function() {
    function Utils() {}

    return Utils;

  })();

  define([]);

}).call(this);

//# sourceMappingURL=_utils_.map
