// Generated by CoffeeScript 1.7.1

/*define [
   *'cs!controller'
   *'cs!view'
   *'regular'
], () ->
 */

(function() {
  emo$.Engine.Utils.FileReader = (function() {
    function FileReader() {}

    FileReader.readFile = function(fileName) {
      var file;
      file = null;
      $.ajax({
        url: fileName,
        async: false,
        crossDomain: true,
        success: function(data) {
          return file = data;
        },
        error: function(e) {
          return console.log(e);
        }
      });
      return file;
    };

    FileReader.parseLine = function(line) {
      var ret;
      return ret = null;
    };

    return FileReader;

  })();

}).call(this);

//# sourceMappingURL=file.reader.map
