// Generated by CoffeeScript 1.7.1
(function() {
  emo$.api.classes = (function() {
    function classes() {}

    return classes;

  })();

  define([], function() {});

}).call(this);

//# sourceMappingURL=_classes_.map
