// Generated by CoffeeScript 1.7.1
(function() {
  emo$.art = (function() {
    function art() {}

    return art;

  })();

  define(['./sketch/_sketch_.js'], function() {});

}).call(this);

//# sourceMappingURL=_art_.map
