// Generated by CoffeeScript 1.7.1
(function() {
  emo$.api = (function() {
    function api() {}

    return api;

  })();

  define(['./inits/_inits_.js', './classes/_classes_.js'], function() {});

}).call(this);

//# sourceMappingURL=_api_.map
