// Generated by CoffeeScript 1.7.1
(function() {
  var FolderLoader;

  FolderLoader = (function() {
    function FolderLoader() {}

    define([], function() {});

    return FolderLoader;

  })();

}).call(this);

//# sourceMappingURL=folder.map
