// Generated by CoffeeScript 1.7.1
(function() {
  emo$.Engine.Emotion.Helpers = (function() {
    function Helpers() {}

    return Helpers;

  })();


  /*define [
    './heuristics.js',
    './lexical.js',
    './parsing.js',
  ], () ->
   */

}).call(this);

//# sourceMappingURL=_helpers_.map
