// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    return grunt.registerTask('_concat_', "concatenates all js files in a directory into _dirName_.js", function() {
      return grunt.file.expand("./modules/*").forEach(function(dir) {
        var concat;
        concat = grunt.config.get('concat') || {};
        concat[dir] = {
          src: ['/modules/' + dir + '/js/*.js', '!/modules/' + dir + '/js/compiled.js'],
          dest: '/modules/' + dir + '/js/compiled.js'
        };
        grunt(config.set('concat', concat));
        return grunt.task.run('concat');
      });
    });
  };

}).call(this);

//# sourceMappingURL=_concat_.map
